POST http://localhost:3333/videos
Content-Type: application/json 

{
    "title": "Vídeo node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/905b42cb-7031-4860-a2d7-5d018b33583c
Content-Type: application/json 

{
    "title": "Vídeo 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/905b42cb-7031-4860-a2d7-5d018b33583c
